{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "nexuscommerce.labels" $ | nindent 4 }}
    {{- include "nexuscommerce.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "nexuscommerce.selectorLabels" (dict "name" $name "root" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexuscommerce.selectorLabels" (dict "name" $name "root" $) | nindent 8 }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ include "nexuscommerce.image" (dict "name" $name "root" $) }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
          {{- if or $svc.env $svc.secretEnv }}
          env:
            {{- range $key, $value := $svc.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secretKey := $svc.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: nexuscommerce-secrets
                  key: {{ $secretKey }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- if ne $name "storefront" }}
          {{- if ne $name "admin" }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
          {{- end }}
{{- end }}
