apiVersion: v1
kind: Secret
metadata:
  name: nexuscommerce-secrets
  labels:
    {{- include "nexuscommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  ordersDbConnection: {{ .Values.secrets.ordersDbConnection | quote }}
  catalogDbConnection: {{ .Values.secrets.catalogDbConnection | quote }}
  jwtSigningKey: {{ .Values.secrets.jwtSigningKey | quote }}
  anthropicApiKey: {{ .Values.secrets.anthropicApiKey | quote }}
