{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "nexuscommerce.labels" $ | nindent 4 }}
    {{- include "nexuscommerce.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nexuscommerce.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
{{- end }}
